### ISSUE TITLE
tensorflow is fast now

### ISSUE THREAD

**Issue by titusnicolae** [zer0n/deepframeworks#16]

**Comment by zer0n** [comment]
Aware. I'll update the post soon. It's already overdue :).

On Wed, May 4, 2016, 10:04 AM Titus Nicolae <notifications@github.com>
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zer0n/deepframeworks/issues/16>
>
-- 

Sent while mobile

**Comment by zer0n** [comment]
Updated
