### ISSUE TITLE
Module deployment

### ISSUE THREAD

**Issue by nicholas-leonard** [zer0n/deepframeworks#23]
I disagree with your review of Torch on [Module deployement](https://github.com/zer0n/deepframeworks#model-deployment). Lua and Torch are easily deployed on smart phones running iOS and Android. As for server to server, Lua can be interfaced with C, C++, CUDA, Java, Python and many other languages. This makes it easy to integrate into existing systems, i.e. to deploy. I agree that it has poor visualisation libraries. So 4 and 1/2 stars instead of 3?

**Comment by zer0n** [comment]
As I mentioned: 

> the bigger problem is integration, at API level, with a larger production pipeline

Again, the whole rating thing is highly subjective. If you think it's a 5, then it's 5 for you and like-minded folks :). Based on my experience working with teams deploying ML models, I can't give it a higher rating.
